abstractnode.h correction of grammar
QuasarApp/Heart pull request #19
Opened 2021-03-05 10:58 UTC by Oleg-designer

ref #16

2021-03-05 17:26 UTC, EndrII commented
please solve all conflicts

2021-03-09 13:34 UTC, EndrII commented
solve please conflicts

2021-03-09 13:41 UTC, EndrII requested changes

2021-03-09 13:41 UTC, EndrII commented on Heart/AbstractSpace/keystorage.h
> +     * @brief check This method fore validation signed message
May be you mean 'for'

2021-03-09 13:43 UTC, EndrII commented on Heart/AbstractSpace/keystorage.h
> +/* what you mean "concat" maybe "contact"? */
this is "concatenate "

2021-03-09 13:44 UTC, Oleg-designer commented on Heart/AbstractSpace/keystorage.h
> +     * @brief check This method fore validation signed message
Yes. Thanks.

2021-03-09 13:45 UTC, Oleg-designer commented on Heart/AbstractSpace/keystorage.h
> +/* what you mean "concat" maybe "contact"? */
Thanks

2021-03-10 07:39 UTC, EndrII requested changes

2021-03-10 07:39 UTC, EndrII commented on Heart/AbstractSpace/packages/closeconnection.h
> + * This need becouse QAbstractSocket emit error when connection closed from remote node.
```suggestion
 * This is necessary because QAbstractSocket emit error when connection closed from remote node.
```

2021-03-10 12:56 UTC, EndrII requested changes

2021-03-10 12:56 UTC, EndrII commented on Heart/DataBaseSpace/databasenode.h
> +     * @return true if data sender successful.
this i meant 'send'

This method return true if data sender successful.

```suggestion
     * @return true if a data send successful.
```

2021-03-10 12:56 UTC, EndrII commented on Heart/DataBaseSpace/databasenode.h
> +     * @return true if data sender seccussful.
```suggestion
     * @return true if a data send successful.
```

2021-03-10 15:15 UTC, EndrII commented
after the merge, the project is not going to be assembled, judging by the log
you accidentally dubbed the **setSct** function 
[stdio(15).log](https://github.com/QuasarApp/Heart/files/6116851/stdio.15.log)

2021-03-11 07:09 UTC, EndrII requested changes

2021-03-11 07:09 UTC, EndrII commented on Heart/DataBaseSpace/databasenode.h
> +                                     const Permission& permision) const;
your remove last changes of the functions signature
return the defaultPermision argument into function

2021-03-11 07:24 UTC, EndrII requested changes

2021-03-11 07:24 UTC, EndrII commented on Heart/DataBaseSpace/databasenode.h
> +                                     const Permission& permision)
```suggestion
                                     const Permission& permision,
```

2021-03-11 07:54 UTC, EndrII requested changes

2021-03-11 07:54 UTC, EndrII commented on Heart/DataBaseSpace/isqldbcache.h
> + * @brief The SqlDBCasheWriteMode enum contains list of available modes of write data to database.
```suggestion
 * @brief The SqlDBCasheWriteMode enum contains list of available modes of write data into database.
```

2021-03-12 13:29 UTC, EndrII commented
Done. thanks for your work

2021-03-12 13:29 UTC, merged